name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: echo
      run: echo ${PWD}

    - name: submodule
      run: git submodule init; git submodule update;
      
    - name: ls
      run: ls third-party/cutest

    - name: build
      run: bash make;
