name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: submodule
      run: git submodule init; git submodule update;

    - name: build
      run: make

    - name: ls
      run: ls -l install/include
